// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43KhC_0sGci0qguUyU6gsTYknaO4UnAw',
    appId: '1:215697649302:web:00456194dca04e93645cb7',
    messagingSenderId: '215697649302',
    projectId: 'tic-tac-toe-765e4',
    authDomain: 'tic-tac-toe-765e4.firebaseapp.com',
    databaseURL:
        'https://tic-tac-toe-765e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-765e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDindhkwUWJnOjObwNTei-3ZyACiZi6wAk',
    appId: '1:215697649302:android:a5d4a0ef9c5fbaf4645cb7',
    messagingSenderId: '215697649302',
    projectId: 'tic-tac-toe-765e4',
    databaseURL:
        'https://tic-tac-toe-765e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-765e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfs8CdyStnxWcR1dFZ9pLeIiUeLpjeII',
    appId: '1:215697649302:ios:0259e0d19132bb7b645cb7',
    messagingSenderId: '215697649302',
    projectId: 'tic-tac-toe-765e4',
    databaseURL:
        'https://tic-tac-toe-765e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-765e4.firebasestorage.app',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfs8CdyStnxWcR1dFZ9pLeIiUeLpjeII',
    appId: '1:215697649302:ios:0259e0d19132bb7b645cb7',
    messagingSenderId: '215697649302',
    projectId: 'tic-tac-toe-765e4',
    databaseURL:
        'https://tic-tac-toe-765e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-765e4.firebasestorage.app',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA43KhC_0sGci0qguUyU6gsTYknaO4UnAw',
    appId: '1:215697649302:web:f9c920187d69bb44645cb7',
    messagingSenderId: '215697649302',
    projectId: 'tic-tac-toe-765e4',
    authDomain: 'tic-tac-toe-765e4.firebaseapp.com',
    databaseURL:
        'https://tic-tac-toe-765e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-765e4.firebasestorage.app',
  );
}
